baseurl: https://blog.kmtea.eu
languageCode: zh-cn
theme: stack
paginate: 5
title: "酷玛阁 | KumaTea's Blog"

timeout: 120s

#languages:
#  zh-cn:
#    languageName: 中文
#    title: 酷玛阁
#    weight: 1
#  en:
#    languageName: English
#    title: KumaTea's blog
#    weight: 2

# Change it to your Disqus shortname before using
disqusShortname: kumatea

# GA Tracking ID
googleAnalytics: G-P86D5805EG

# Theme i18n support
# Available values: ar, ca, de, el, en, es, fr, hu, id, it, ja, ko, nl, pt-br, th, uk, zh-cn, zh-hk, zh-tw
DefaultContentLanguage: zh-cn

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage: true

permalinks:
  posts: /p/:slug/
  pages: /:slug/

params:
  mainSections:
    - posts
  featuredImageField: image
  rssFullContent: true
  favicon: //kmtea.eu/res/2206/avatar.png

  footer:
    since: 2022
    customText:

  dateFormat:
    date: 2006-01-02
    published: 2006-01-02
    publishedShort: 01-02
    lastUpdated: 2006-01-02
    lastUpdatedShort: 01-02
    lastUpdatedTime: 01-02 15:04
    expiryDate: 2006-01-02

  sidebar:
    emoji:
    subtitle:
    avatar:
      enabled: true
      local: false
      src: //kmtea.eu/res/2206/avatar.png

  article:
    math: false
    toc: true
    readingTime: false
    license:
      enabled: true
      default: Licensed under CC BY-NC-SA 4.0

  comments:
      enabled: true
      provider: disqus

      disqusjs:
        shortname:
        apiUrl:
        apiKey:
        admin:
        adminLabel:

#      provider: giscus
#
#      giscus:
#          repo: KumaTea/blog
#          repoID: R_kgDOHa9iHQ
#          category: Q&A
#          categoryID: DIC_kwDOHa9iHc4CXYZJ
#          mapping: pathname
#          strict: 1
#          lightTheme: preferred_color_scheme
#          darkTheme: preferred_color_scheme
#          reactionsEnabled: 1
#          emitMetadata: 0
#          inputPosition: top
#          lang: zh-CN

  widgets:
    homepage:
      - type: search
      - type: archives
        params:
          limit: 5
      - type: categories
        params:
          limit: 10
      - type: tag-cloud
        params:
          limit: 10
    page:
      - type: toc

  opengraph:
    twitter:
      # Your Twitter username
      site: KumaTea0

      # Available values: summary, summary_large_image
      card: summary_large_image

  defaultImage:
    opengraph:
      enabled: false
      local: false
      src:

  colorScheme:
    # Display toggle
    toggle: true

    # Available values: auto, light, dark
    default: auto

  imageProcessing:
    cover:
      enabled: true
    content:
      enabled: true

### Custom menu
### See https://docs.stack.jimmycai.com/configuration/custom-menu.html
### To remove about, archive and search page menu item, remove `menu` field from their FrontMatter
menu:
  main: [ ]

#  social:
#    - identifier: github
#      name: GitHub
#      url: https://github.com/CaiJimmy/hugo-theme-stack
#      params:
#        icon: brand-github
#
#    - identifier: twitter
#      name: Twitter
#      url: https://twitter.com
#      params:
#        icon: brand-twitter

related:
  includeNewer: true
  threshold: 60
  toLower: false
  indices:
    - name: tags
      weight: 100

    - name: categories
      weight: 200

markup:
  goldmark:
    renderer:
      ## Set to true if you have HTML content inside Markdown
      unsafe: true
  tableOfContents:
    endLevel: 4
    ordered: true
    startLevel: 2
  highlight:
    noClasses: false
    codeFences: true
    guessSyntax: true
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    tabWidth: 4
